// src/renderer/src/components/ResultDisplay.vue
<script setup lang="ts">
import { computed } from 'vue'
import { Button } from '@/components/ui/button'
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert'
import { CheckCircle2, FolderOpen, RefreshCcw } from '@lucide/vue'
import { getErrorMessage, isApiError, showOutputInFolder } from '@/lib/api'

interface Props {
  outputPath: string
  rowCount: number
  columnsAnonymized: number
  duration: number
}

const props = defineProps<Props>()

const emit = defineEmits<{
  reset: []
  error: [message: string]
}>()

const durationText = computed(() => {
  if (props.duration < 1000) {
    return `${props.duration}ms`
  }
  return `${(props.duration / 1000).toFixed(2)}s`
})

const statsText = computed(() => {
  const rows = props.rowCount.toLocaleString()
  const cols = props.columnsAnonymized
  const colText = cols === 1 ? 'column' : 'columns'
  return `${rows} rows processed, ${cols} ${colText} anonymized in ${durationText.value}`
})

function handleReset(): void {
  emit('reset')
}

async function handleOpenFolder(): Promise<void> {
  const response = await showOutputInFolder({ outputPath: props.outputPath })

  if (isApiError(response)) {
    emit('error', getErrorMessage(response))
  }
}
</script>

<template>
  <div class="space-y-4">
    <Alert class="border-green-500/50 bg-green-900/20">
      <CheckCircle2 class="h-5 w-5 text-green-500" />
      <AlertTitle class="text-green-400">Success!</AlertTitle>
      <AlertDescription class="space-y-2">
        <p>Your file has been successfully anonymized.</p>
        <p class="font-mono text-sm text-muted-foreground">
          {{ outputPath }}
        </p>
        <p class="text-sm text-muted-foreground">
          {{ statsText }}
        </p>
      </AlertDescription>
    </Alert>

    <div class="flex flex-wrap gap-2">
      <Button variant="outline" @click="handleOpenFolder">
        <FolderOpen class="mr-2 h-4 w-4" />
        Open Folder
      </Button>
      <Button @click="handleReset">
        <RefreshCcw class="mr-2 h-4 w-4" />
        Anonymize Another File
      </Button>
    </div>
  </div>
</template>

// frontend/src/components/ResultDisplay.tsx
import { CheckCircle2, FolderOpen, RefreshCcw } from 'lucide-react'
import { openOutputLocation } from '../tauri'
import type { AnonymizeData } from '../types'
import { messageFrom } from '../utils/errors'
import { formatResultStats } from '../utils/format'
import { Alert } from './Alert'

export function ResultDisplay({
  result,
  onReset,
  onError,
}: {
  result: AnonymizeData
  onReset: () => void
  onError: (message: string) => void
}) {
  async function handleOpenFolder() {
    try {
      await openOutputLocation(result.outputPath)
    } catch (caught) {
      onError(messageFrom(caught))
    }
  }

  return (
    <div className="result-stack">
      <Alert variant="success" icon={<CheckCircle2 aria-hidden="true" />}>
        <h2>Success!</h2>
        <div className="result-description">
          <p>Your file has been successfully anonymized.</p>
          <p className="mono muted-text result-path">{result.outputPath}</p>
          <p className="muted-text text-sm">{formatResultStats(result)}</p>
        </div>
      </Alert>

      <div className="result-actions">
        <button type="button" className="button button-outline" onClick={() => void handleOpenFolder()}>
          <FolderOpen aria-hidden="true" />
          Open Folder
        </button>
        <button type="button" className="button button-primary" onClick={onReset}>
          <RefreshCcw aria-hidden="true" />
          Anonymize Another File
        </button>
      </div>
    </div>
  )
}
